version: "3.7"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD : true
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
  app:
    build: .
    image: lingga1200/go-api:${APP_VERSION}
    container_name: go-api
    ports:
      - "${APP_PORT}:8080"
    environment:
      SECRET_JWT: ${JWT_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_HOST: host.docker.internal
      DB_NAME: ${DB_NAME}
    restart: always